### ISSUE TITLE
Protect to remove IE conditional comment

### ISSUE THREAD

**Issue by PixelT** [RnbWd/gulp-strip-comments#10]
Automatically ignore to remove conditional Internet Explorer comment, for example:
```
<!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
```

**Comment by vitaly-t** [comment]
@PixelT you do know that the last browser that supported HTML conditional comments was now prehistoric Internet Explorer 9 ;)

**Comment by vitaly-t** [comment]
@PixelT The underline library [decomment](https://github.com/vitaly-t/decomment) 0.8.1 now supports it.

This library just needs to update its dependency. In the meantime, you can use [gulp-decomment](https://github.com/vitaly-t/gulp-decomment), which is the same, except it doesn't set option `safe` by default, it uses the default from [decomment](https://github.com/vitaly-t/decomment), so you need to set it explicitely ;)

**Comment by RnbWd** [comment]
updated
