### ISSUE TITLE
Bug: unexpected token with gulp-babel

### ISSUE THREAD

**Issue by kevincaradant** [RnbWd/gulp-strip-comments#11]
Hi

I met a new problem. I don't know if the problem comes from `gulp-strip-comments`or `gulp-babel` so i ask here.

I get this error : 
![image](https://cloud.githubusercontent.com/assets/6093175/13553852/5258309a-e397-11e5-8a6d-eb7ca593b4ad.png)

And my file app.js line 54: 
![image](https://cloud.githubusercontent.com/assets/6093175/13553874/dad402d2-e397-11e5-8ee2-0a9e505af3b4.png)

So the problem is about the comment.

Any idea why ? :)

Thank you 

Edit:

I'm running on Windows 10 Pro (x64) 

My gulp task  ( not work ) :
```
gulp.src('src/app/app.js')
	.pipe($.if($.env.isDev, $.sourcemaps.init()))
	.pipe($.if($.env.isProd, $.stripComments()))
	.pipe($.babel())
	.pipe($.if($.env.isDev, $.sourcemaps.write()))
	.pipe(gulp.dest('build/js/'))
```
 
Work :
```
gulp.src('src/app/app.js')
	.pipe($.if($.env.isDev, $.sourcemaps.init()))
	.pipe($.babel())
	.pipe($.if($.env.isDev, $.sourcemaps.write()))
	.pipe(gulp.dest('build/js/'))
```

**Comment by vitaly-t** [comment]
It is impossible to see what the problem is, from what you published:

* What is the difference in comments between the source and the destination files?
* Where is the actual problem in the destination file?

**Comment by kevincaradant** [comment]
Yes sorry. 

Maybe that can help you 

Without stripComment() : 

```
let app = angular.module('CUSTOM_NAME_OF_THE_APP', [
	'ngMockE2E',
	'ngAnimate',
	'ui.router',
	'anim-in-out',
	'ui.bootstrap',
	'ngSanitize',
	'pascalprecht.translate',
	'angular-loading-bar',
	'rx',
	'ngWebworker'
]);
let languages = ['en', 'fr'];

(() => {
	app.config(($compileProvider, $httpProvider, $locationProvider, $stateProvider, $provide, $urlRouterProvider, $translateProvider) => {
		$compileProvider.debugInfoEnabled(true);

		$httpProvider.defaults.cache = true;

		$stateProvider
		.state('home', {
			url: '/home',
			views: {
				mainView: {templateUrl: './html/views/home.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page1', {
			url: '/page1',
			views: {
				mainView: {templateUrl: './html/views/page1.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page2', {
			url: '/page2',
			views: {
				mainView: {templateUrl: './html/views/page2.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page3', {
			url: '/page3',
			views: {
				mainView: {templateUrl: './html/views/page3.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		});

		// default redirection to /home
		$urlRouterProvider.otherwise('/home');

		// load languages from json files (when needed)
		$translateProvider.useStaticFilesLoader({
			prefix: './languages/',
			suffix: '.json'
		});

		// handle multiple locales for one language
		$translateProvider.registerAvailableLanguageKeys(languages, {
			'en_*': 'en',
			'fr_*': 'fr'
		});

		// define sanitize strategy and prefered language
		$translateProvider.useSanitizeValueStrategy('escape');
		$translateProvider.determinePreferredLanguage();
	});
})();
```

With StripComment() : 
```|
let app = angular.module('CUSTOM_NAME_OF_THE_APP', [
	'ngMockE2E',
	'ngAnimate',
	'ui.router',
	'anim-in-out',
	'ui.bootstrap',
	'ngSanitize',
	'pascalprecht.translate',
	'angular-loading-bar',
	'rx',
	'ngWebworker'
]);
let languages = ['en', 'fr'];

(() => {
	app.config(($compileProvider, $httpProvider, $locationProvider, $stateProvider, $provide, $urlRouterProvider, $translateProvider) => {
		$compileProvider.debugInfoEnabled(true);

		$httpProvider.defaults.cache = true;

		$stateProvider
		.state('home', {
			url: '/home',
			views: {
				mainView: {templateUrl: './html/views/home.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page1', {
			url: '/page1',
			views: {
				mainView: {templateUrl: './html/views/page1.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page2', {
			url: '/page2',
			views: {
				mainView: {templateUrl: './html/views/page2.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		})

		.state('page3', {
			url: '/page3',
			views: {
				mainView: {templateUrl: './html/views/page3.html'},
				rightMenuView: {templateUrl: './html/views/rightMenu.html'}
			}
		});

```

So when i use stripComment() , i haven't the end of the file after the first comment :/

**Comment by vitaly-t** [comment]
You must be using some old version of the library, because the problem does not reproduce in the latest version.

Update your library version and try again.

**Comment by vitaly-t** [comment]
UPDATE: I cannot reproduce the problem in any of the versions of the library...

**Comment by kevincaradant** [comment]
I tried gulp-decomment V0.8.1 , same problem :/.
Something wrong but i can't find it .

This is the sources where i met the problem : 
https://github.com/kevincaradant/web-template

**Comment by vitaly-t** [comment]
I can't see that content within the source you gave here...

**Comment by vitaly-t** [comment]
Nevermind, found it: https://github.com/maxime1992/web-template/blob/master/src/app/app.js

But that's from the original repo, not the fork you provided.

**Comment by kevincaradant** [comment]
https://github.com/kevincaradant/web-template/tree/master/src/app , it's the same. I'm working with maxime , so we have a repo very similar

**Comment by vitaly-t** [comment]
I have found the problem.

You are trying to decomment a file on Windows that was encoded using Linux-type end-of line.

For that you need to use option [platform](https://github.com/vitaly-t/decomment#optionsplatform--string) to override the default behavior.

**Comment by vitaly-t** [comment]
i.e. call `.pipe($.if($.env.isProd, $.stripComments({platform: 'auto'})))`

**Comment by vitaly-t** [comment]
This is not the first time this came up. I am now seriously considering to make `auto` the default.

**Comment by kevincaradant** [comment]
Mhh, always the same problem in my case :/

**Comment by vitaly-t** [comment]
Pardon, are you saying you added option `platform: 'auto'` and it still doesn't work?

The only way it is possible is if you didn't pass it in correctly. 

You need to pass it in in the way consistent with this official example:

```js
var gulp = require('gulp');
var strip = require('gulp-strip-comments');

gulp.task('default', function () {
  return gulp.src('template.js')
    .pipe(strip({platform: 'auto'}))
    .pipe(gulp.dest('dist'));
});
```

**Comment by kevincaradant** [comment]
OK , i don't know what can i say ...

On my other computer it's good.

On my actual computer, i deleted and reinstall twice and now that work ...

By precaution, i will add your option : `{platform: 'auto'}`, that can be usefull. I think you can set it by default like you mentioned before. 

I can't say you the solution because now , without any option : this works : 
`.pipe($.if($.env.isProd, $.stripComments()))`

**Comment by vitaly-t** [comment]
Don't, I'm releasing an updated version of `decomment` now with option `platform` retired, it is always `auto` now, that's it. Will let you know when it is ready, in a moment ;)

**Comment by kevincaradant** [comment]
All right  :) . Mhh BTW, i replace gulp-strip-comment by gulp-decomment ?

**Comment by vitaly-t** [comment]
I have released the new [version 0.8.2 of decomment](https://github.com/vitaly-t/decomment/releases/tag/v.0.8.2).

As for gulp-strip-comment versus gulp-decomment, the only difference is that gulp-strip-comment overrides option [safe](https://github.com/vitaly-t/decomment#optionssafe--boolean) to be `true` by default, which gulp-decomment doesn't, it just uses all the defaults as they are within the decomment library.

**Comment by kevincaradant** [comment]
Thank you fr the explanations ;) , Just to know , if you released decomment , gulp-decomment is it updated too ?

**Comment by vitaly-t** [comment]
It just has been ;)

**Comment by kevincaradant** [comment]
OK perfect :)
