### ISSUE TITLE
update for option `ignore`

### ISSUE THREAD

**Issue by vitaly-t** [RnbWd/gulp-strip-comments#12]
@RnbWd when you get a moment, please update documentation about option [ignore](https://github.com/vitaly-t/decomment#optionsignore--regexp--regexp) that was recently implemented.

See why it was added:

* https://github.com/vitaly-t/decomment/issues/8
* https://github.com/vitaly-t/decomment/pull/6

**Comment by RnbWd** [comment]
updated docs - :+1:
