### ISSUE TITLE
.text() does not handle multiline /* comments

### ISSUE THREAD

**Issue by davewallace** [RnbWd/gulp-strip-comments#21]
Hi,

I was stumped for a while on this one, thinking it was the fault of gulp-sourcemaps that I could not harvest an accurate mapping from source files. I tried all sorts of things, but in the end it turned out to be this lib.

Basically, single line comments in the form `//` or `/* */` are handled as expected, but in the form:

```
/**
 *
 * etc etc..
 **/
```

..are not.

My use case is legal document headers present in source .scss files which we cannot remove and so they must be processed.

I'm a bit over it after all of that effort, but if you need a reduced test case to replicate, gimme a couple of days and I'll throw my test repo up.

Ta,
d

**Comment by vitaly-t** [comment]
@davewallace If you come up with an example that doesn't work, you should log the issue against [decomment](https://github.com/vitaly-t/decomment), being the driver.

**Comment by davewallace** [comment]
Alright, thanks.
