### ISSUE TITLE
Removes IE conditional comments

### ISSUE THREAD

**Issue by alenvuletic** [RnbWd/gulp-strip-comments#22]
Removes IE conditional comments like this one in `.html` files:
`<!--[if gte mso 9]><![endif]-->`

More info about IE conditional comments: https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx

**Comment by vitaly-t** [comment]
@alenvuletic use option [safe](https://github.com/RnbWd/gulp-strip-comments#optionssafe--boolean) for that.

**Comment by alenvuletic** [comment]
Thanks @vitaly-t !
