### ISSUE TITLE
Upgrade to strip-comments-v0.4.2

### ISSUE THREAD

**Issue by epicoxymoron** [RnbWd/gulp-strip-comments#4]
Please consider cutting a new release using strip-comments v0.4.2, the latest release.  It's parser-based, rather than regex-based, which means it can do a better job at handling comment-looking strings that are... well, just strings.

**Comment by RnbWd** [comment]
There are some breaking changes in the API which lead to some unexpected behavior - `gulp-strip-comments@1.1.1` is using `strip-comment@^0.4.1` which should pull `v0.4.2` by default. I marked them as deprecated - but it's not pulled from npm  (only a warning) - but everything in the `v1.1.x` branch will use `strip-comments@0.3.x`. I agree that a parser is better than regex - and I'll probably just use a custom parser for this repo  based on  [gulp-strip-json-comments](https://github.com/sindresorhus/gulp-strip-json-comments) / [babel-plugin-strip-comments](https://github.com/thejameskyle/babel-plugin-remove-comments) / and the original `strip-comments` repo.
