### ISSUE TITLE
Another version :)

### ISSUE THREAD

**Issue by vitaly-t** [RnbWd/gulp-strip-comments#6]
Thank you for this library, i'm looking at it as a template for implementing my own version of,...the same, pretty much :)

The thing is, I needed a plugin like this, but I had too many problems with the strip-comments component, so I ended up writing one of my own - [decomment](https://github.com/vitaly-t/decomment).

Now I started on [gulp-decomment](https://github.com/vitaly-t/gulp-decomment), but I have no experience writing gulp plugins. This is where your code helps me a lot, so thank you again!

And if you like writing gulp plugins, and would consider helping me with this, much appreciate it!

In fact, I would have no problem transfering the ownership of [gulp-decomment](https://github.com/vitaly-t/gulp-decomment) to yourself, if you want it! ;)

**Comment by RnbWd** [comment]
yes! I should probably add you to this repo as well

**Comment by vitaly-t** [comment]
Thanks!
