### ISSUE TITLE
syncing with gulp-decomment

### ISSUE THREAD

**Issue by vitaly-t** [RnbWd/gulp-strip-comments#7]
This is following your question: [Need help testing](https://github.com/vitaly-t/gulp-decomment/issues/3)

I've just done a commit, in which the following changes were made:

* Implementation is fully copied from gulp-decomment
* All tests fully copied from gulp-decomment
* All Prod+Dev dependencies taken from gulp-decomment, replacing the old ones.
* `scripts` extended in `package.json` for testing + code coverage + travis integration
* `.travis.yml` content taken from gulp-decomment

Your library is now 100% ready to provide code coverage also. You can run `npm run coverage` for that. And you can integrate it into the Coveralls, like I did.

I would suggest to reconsider the documentation though, see how I did it for [gulp-decomment](https://github.com/vitaly-t/gulp-decomment) and [grunt-decomment](https://github.com/vitaly-t/grunt-decomment). There is no point trying to re-document things, it is best to provide references only.

**Comment by vitaly-t** [comment]
UPDATE: Added coveralls package also.

Now if you register yourself with coveralls, all you have to do in the project:
open file `.travis.yml`, and replace `npm test` with `npm run travis`.

**Comment by RnbWd** [comment]
Wow, thank you so much!! Yeah I can def. add a coveralls link. Regarding documentation and style, I agree there should be links to `decomment` - but I also like having a minimalistic summary of each method too. I follow in the shadow of [sindresorhus](https://github.com/sindresorhus?tab=repositories), everything I initially wrote was inspired by his style of maintaining modules. I use one of his modules to sync the github repo with npm  - I'm just trying to be consistent.

So I wrote some [milestones](https://github.com/RnbWd/gulp-strip-comments/milestones?state=open) for `v3.0.0` - one involves detecting files and calling methods based on filetype, which would require an additional option (to turn it off or on). Gulp's vinyl format provides a lot metadata about the files being passed in, which is powerful to leverage and 'relatively' unique to gulp. I also want to explore building plugins for browserify, webpack, maybe babel and few others. I know there's a lot of redundancy in the ecosystem, but each has it's own niche. These plugins just make it simple for people consume the core libraries being wrapped - and it also gives it more exposure. Sometimes I dream about a universal plugin system.. but that's still years off :)

**Comment by vitaly-t** [comment]
I don't know how gulp works with file filters, but I'm guessing there a module for that already, so you can redirect its output file names into your code for processing. I'm not sure you would need to change your library for that.

My `grunt-decomment` though had to be changed to support file paths and filters, because grunt works differently, through configurators.

**Comment by vitaly-t** [comment]
As far as I know, [glob](https://github.com/isaacs/node-glob) is what to be used within gulp system to get all the file filters. Or you can use one of its derivatives. And since you like that guys work, here's one related: [gulp-filter](https://github.com/sindresorhus/gulp-filter).

But I think you won't need to change your library for that.

**Comment by vitaly-t** [comment]
>These plugins just make it simple for people consume the core libraries being wrapped - and it also gives it more exposure. Sometimes I dream about a universal plugin system.. but that's still years off :)

In that sentiment I just wrote [text-wrap](https://github.com/vitaly-t/text-wrap), plus [grunt-file-wrap](https://github.com/vitaly-t/grunt-file-wrap) ;)

By the way, I haven't even created any `gulp-file-wrap`, and the name is still vacant on NPM. Feel free to get the pace on this one, if you want to scratch your gulp skills ;)

**Comment by RnbWd** [comment]
Question, should i omit .coveralls.yml token on github?

**Comment by vitaly-t** [comment]
>Question, should i omit .coveralls.yml token on github?

Yeah, it's not needed, at least not within the setup that I provided.

**Comment by RnbWd** [comment]
So I actually have a module that I've been wanting to turn into a plugin for a long time - it needs refactoring - [file-indexer](https://github.com/RnbWd/file-indexer)

**Comment by RnbWd** [comment]
i got the coverage working :+1: now I just need to clean up the readme

**Comment by vitaly-t** [comment]
good job ;)

**Comment by RnbWd** [comment]
To answer your question about gulp, I think everything i would need is in the gulp-util library, I'm a little rusty but familiar with the buffer syntax. The *biggest* question is arbitrary - 'what decommend method should be used based on file ext?) It can't be right 100% of the time, so I'll make it optional.

**Comment by vitaly-t** [comment]
decomment is quite neutral about the file extension, only the actual content that matters. But for extensions like CSS, CPP, H you would need to use `decomment.text`, because the default one can handle only HTML and JavaScript/JSON.

**Comment by RnbWd** [comment]
Yeah, it's 100% within the scope of this gulp plugin, it's not something that the `decomment` core library should worry about IMO - it's just meant to simplify gulp tasks so you only have to write one task, and pipe everything into that single task.
