### ISSUE TITLE
version 0.8 and option `platform`

### ISSUE THREAD

**Issue by vitaly-t** [RnbWd/gulp-strip-comments#8]
[decomment](https://github.com/vitaly-t/decomment) 0.8 has been extended with a very useful option [platform](https://github.com/vitaly-t/decomment#optionsplatform--string), whenever you find time to update your library ;)

Cheers!

**Comment by vitaly-t** [comment]
@RnbWd Will you find time to re-release the library with the latest decomment?

**Comment by vitaly-t** [comment]
@RnbWd Sorry to bother you again, but are you still planning to support this library? It's just has been a while since you even replied.

**Comment by RnbWd** [comment]
Sorry totally missed this - I should put you on co-signer npm so you can also publish if I forget. (I know it's possible just haven't done it before.) - if the package.json is written like '^0.8.0' it won't need to be touched again until '0.9.x'

**Comment by RnbWd** [comment]
Just added you :)

**Comment by RnbWd** [comment]
didn't see option platform.. wait a sec

**Comment by RnbWd** [comment]
okay that's fixed, turned out there wasn't trim - safe - or platform. look at the source code for future ref. in case I'm not avail - you have equal permissions to publish on both npm and github

**Comment by RnbWd** [comment]
at least i think github.. 100% sure about npm though it's in your profile
